/**
 *
 * $Id$
 */
package net.atos.optimus.m2m.engine.sdk.tom.validation;

import net.atos.optimus.m2m.engine.sdk.tom.ExternalTransformation;
import net.atos.optimus.m2m.engine.sdk.tom.TransformationSet;
import net.atos.optimus.m2m.engine.sdk.tom.TransformationSetExtension;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.atos.optimus.m2m.engine.sdk.tom.TransformationSets}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransformationSetsValidator {
	boolean validate();

	boolean validateTransformationSets(EList<TransformationSet> value);
	boolean validateTransformationSetExtensions(EList<TransformationSetExtension> value);
	boolean validateExternalTransformations(EList<ExternalTransformation> value);
}
